---
- hosts: localhost
  vars_files:
    - properties.yml
  tasks:
     - name: Install redis server
       apt: name=redis-server state=installed

     - name: Bind to local address
       lineinfile: dest=/etc/redis/redis.conf regexp='bind 127.0.0.1' line='bind 127.0.0.1 {{ anycast_ip_redis }}' backup=yes

     - name: Restart redis server
       service: name=redis-server state=restarted

     - name: Wipe out any redis state
       command: redis-cli flushall

     - name: Install Cumulus repos for installing netq
       apt_repository: repo="{{ item }}" state=present update_cache=yes
       with_items:
         - deb http://repo3.cumulusnetworks.com/repo CumulusLinux-3-early-access cumulus
         - deb http://repo3.cumulusnetworks.com/repo CumulusLinux-3 cumulus upstream
         - deb http://repo3.cumulusnetworks.com/repo CumulusLinux-3-updates cumulus upstream

     - name: Install netq on OOB server
       apt: name="python-netq" state=installed allow_unauthenticated=yes

     - name: Configure the agent with the server IP to push
       command: netq add server {{ anycast_ip_redis }}